use_frameworks!

target 'VerticalAlignmentLabel_Example' do
  pod 'VerticalAlignmentLabel', :path => '../'

  target 'VerticalAlignmentLabel_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
